version: '3'
services:
  client:
    container_name: client
    restart: always
    build: ./vue-client
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - '8080:8080'
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: node-app
    volumes:
      - .server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    depends_on:
      - mongo
    env_file: ./server/.env
    environment: 
      - NODE_ENV=development
    ports:
      - "3000:3000"
