version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app-img
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    env_file: .env
    environment: 
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "3000:3000"